version: 0.2

phases:
 install:
  runtime-versions:
   docker: 18
 pre_build:
  commands:
   - $(aws ecr get-login --no-include-email --region us-east-1)
 build:
  commands:
   - cd Authorization-Microservice
   - mvn compile
   - mvn package
   - docker build -t pension/auth .
   - docker tag pension/auth 885843804602.dkr.ecr.us-east-1.amazonaws.com/pensionauth:latest
 post_build:
  commands:
   - docker push 885843804602.dkr.ecr.us-east-1.amazonaws.com/pensionauth:latest
   - printf '[{"name":"auth-container","imageUri":"%s"}]' 885843804602.dkr.ecr.us-east-1.amazonaws.com/pensionauth:latest > taskdefinition.json
artifacts:
 files:
  - Authorization-Microservice/taskdefinition.json
